version: '2'
services:
    mongodb:
        image: mongo:3.0.5
        container_name: "mongodb"
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        ports:
            - 27017:27017
        volumes:
           - './docker/data/mongodb:/data/db'
        restart: always